version: "1"
services:
  pion:
    image: "postgres:14"
    container_name: "pion"
    ports:
      - "5432:5432"
    volumes:
      - "./schema/pion.sql:/docker-entrypoint-initdb.d/pion.sql"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "testpassword"
      POSTGRES_DB: "postgres"
volumes:
  data: